version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
    - "8080:80"
    - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - /mnt/c/Users/JohnBrian/.aspnet/https/
      # - ${APPDATA}/MicrosoftUserSecrets:/mnt/c/Users/JohnBrian/AppData/Roaming/Microsoft/UserSecrets:ro
      # - ${USERPROFILE}/.aspnet/https:/mnt/c/Users/JohnBrian/AppData/Roaming/ASP.NET/Https:ro